<a href="https://colab.research.google.com/github/HMBinara/ML_Project/blob/main/Human_Hydration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Import the libraies

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from google.colab import files

uploaded = files.upload()

df = pd.read_csv('Daily_Water_Intake.csv')

Saving Daily_Water_Intake.csv to Daily_Water_Intake (1).csv

In [4]:
# cheak the colum and row

df.shape

(30000, 7)

In [5]:
# cheak the some information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          30000 non-null  int64
 1   Gender                       30000 non-null  object
 2   Weight (kg)                  30000 non-null  int64
 3   Daily Water Intake (liters)  30000 non-null  float64
 4   Physical Activity Level      30000 non-null  object
 5   Weather                      30000 non-null  object
 6   Hydration Level              30000 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 1.6+ MB

In [7]:
#chaeking the missing value

df.isnull().sum()

Age                            0
Gender                         0
Weight (kg)                    0
Daily Water Intake (liters)    0
Physical Activity Level        0
Weather                        0
Hydration Level                0
dtype: int64

In [9]:
#show the frist row

df.head()

,Age,Gender,Weight (kg),Daily Water Intake (liters),Physical Activity Level,Weather,Hydration Level
0,56,Male,96,4.23,Moderate,Hot,Good
1,60,Male,105,3.95,High,Normal,Good
2,36,Male,68,2.39,Moderate,Cold,Good
3,19,Female,74,3.13,Moderate,Hot,Good
4,38,Male,77,2.11,Low,Normal,Poor