<a href="https://colab.research.google.com/github/HMBinara/ML_Project/blob/main/ProfesinalP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import the Libries

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
import joblib

Load the CSV file

In [3]:
from google.colab import files
uploaded = files.upload()

df = pd.read_csv('job_market.csv')

Saving job_market.csv to job_market.csv

In [5]:
#Show the Frist row
df.head()

,job_title,company,location,job_type,category,salary_min,salary_max,experience_required,publication_date,skills
0,Engineering Manager,DataInc,"San Francisco, CA",Remote,Technology,151082,291345,4.0,2025-11-27,"AWS, Agile, Machine Learning, Kubernetes, Mong..."
1,Engineering Manager,EnterpriseHub,"New York, NY",Remote,Technology,156891,280075,3.0,2025-11-27,"Java, Agile, Git, SQL, Ruby, Go"
2,Engineering Manager,StartupXYZ,"Seattle, WA",Part-time,Technology,152134,280310,4.0,2025-11-27,"AWS, Python, Kubernetes, Git"
3,Lead Engineer,WebDynamics,"Seattle, WA",Full-time,Technology,151918,253988,7.0,2025-11-27,"Agile, Git, Docker, REST APIs, TypeScript"
4,Senior Software Engineer,DigitalWorks,"San Francisco, CA",Full-time,Technology,148141,252584,9.0,2025-11-27,"Agile, Ruby, Docker, Git, JavaScript"

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_title            250 non-null    object
 1   company              250 non-null    object
 2   location             250 non-null    object
 3   job_type             221 non-null    object
 4   category             230 non-null    object
 5   salary_min           250 non-null    int64
 6   salary_max           250 non-null    int64
 7   experience_required  207 non-null    float64
 8   publication_date     250 non-null    object
 9   skills               200 non-null    object
dtypes: float64(1), int64(2), object(7)
memory usage: 19.7+ KB

In [7]:
# 2. Calculate the average salary (Target variable)
df['avg_salary'] = (df['salary_min'] + df['salary_max']) / 2

In [8]:
# 3. Extract Country from Location column
# Example: "Berlin, Germany" -> "Germany"
df['country'] = df['location'].apply(lambda x: x.split(',')[-1].strip())

In [9]:
df.head()

,job_title,company,location,job_type,category,salary_min,salary_max,experience_required,publication_date,skills,avg_salary,country
0,Engineering Manager,DataInc,"San Francisco, CA",Remote,Technology,151082,291345,4.0,2025-11-27,"AWS, Agile, Machine Learning, Kubernetes, Mong...",221213.5,CA
1,Engineering Manager,EnterpriseHub,"New York, NY",Remote,Technology,156891,280075,3.0,2025-11-27,"Java, Agile, Git, SQL, Ruby, Go",218483.0,NY
2,Engineering Manager,StartupXYZ,"Seattle, WA",Part-time,Technology,152134,280310,4.0,2025-11-27,"AWS, Python, Kubernetes, Git",216222.0,WA
3,Lead Engineer,WebDynamics,"Seattle, WA",Full-time,Technology,151918,253988,7.0,2025-11-27,"Agile, Git, Docker, REST APIs, TypeScript",202953.0,WA
4,Senior Software Engineer,DigitalWorks,"San Francisco, CA",Full-time,Technology,148141,252584,9.0,2025-11-27,"Agile, Ruby, Docker, Git, JavaScript",200362.5,CA